### ISSUE TITLE
UI dark text on dark theme, can't read. Anki 2.1.49

### ISSUE THREAD

**Issue by ItsCheif** [ShoroukAziz/Beautify-Anki#60]
On the main menu, the ui text of the Heatmap looks like this:
![image](https://user-images.githubusercontent.com/27285613/160074595-b87981d2-74fe-49a9-99ff-fb71f77ea0ac.png)

If I click on a deck, before I actually go into it, the heatmap ui text looks like this:
![image](https://user-images.githubusercontent.com/27285613/160074641-a7b44bb3-2859-4bbb-a43b-19473e4bfb9b.png)

When reviewing cards, the UI text showing how long it'll be before I see this card again is dark on a dark theme:
![image](https://user-images.githubusercontent.com/27285613/160074684-63052648-f831-4d8b-964c-db4be5eec8b3.png)

**Comment by SweetHeatSteve** [comment]
I have the same exact issue...

**Comment by ItsCheif** [comment]
Another user complained to me about this so I came back to check if anybody has found a solution. Any luck guys?

**Comment by ItsCheif** [comment]
### SOLVED!

Really had a "Fine, I'll do it myself" moment lmao.

### Step 1:
Navigate to the CSS files.

`C:\Users\**yourname**\AppData\Roaming\Anki2\addons21\beautify anki\user_files\assets\css`

### Step 2:
Look for "deckbrowser.css" to fix the Heatmap
Look for "reviewer_bottom.css" to fix the interval time stuff

Open both of them if you want to fix both.

### Step 3:
To fix the **heatmap**, open "deckbrowser.css" and paste in the following:
```
body.nightMode {
  color: white;
  background-size: 100%;

}
```
You'll want to paste it right here like this (see first image): 
![notepad_pbekqhau6R](https://user-images.githubusercontent.com/27285613/199729318-09f4cfbe-2d48-4c67-a8ce-e5c460198aae.png)
https://imgur.com/a/HpkaynV

### Step 4:
To fix the ** Interval times**, open "reviewer_bottom.css" and paste in the following:
```
color: white;
```

You'll want to paste it right here like this (see second image): 
![notepad_umlJnc9ep3](https://user-images.githubusercontent.com/27285613/199729392-7a449a62-e5cb-4704-8b50-9cf941417dd9.png)
https://imgur.com/a/HpkaynV

### Step 5:
Reboot Anki and you should see the changes take effect
